modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/buzzier-bees/issues"
license = "https://github.com/team-abnormals/buzzier-bees/blob/main/LICENSE.txt"

[[mods]]
    modId = "buzzier_bees"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five, hatsondogs, and Farcr"
    displayName = "Buzzier Bees"
    description = '''
    Buzzier Bees expands on the content introduced in 1.15, introducing candles, new building blocks, and more!
    '''

[[dependencies.buzzier_bees]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.buzzier_bees]]
    modId = "forge"
    mandatory = true
    versionRange = "[34.1.42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.buzzier_bees]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.0.6,)"
    ordering = "AFTER"
    side = "BOTH"
